### ISSUE TITLE
I can't run the game 

### ISSUE THREAD

**Issue by tobyplowy** [LordStephen77/DreamBlocks-Beyond-of-Time#3]
@LordStephen77 how do I run the game there's no .jar file?

**Comment by LordStephen77** [comment]
I only published the project created with Gradle. There is still no executable on github. I have to work to optimize everything, and make the first alpha working.

Compiling .jar will be extremely easy to use the Windows, Linux, Mac OS terminal.
I will publish the simple commands to use in the terminal to generate executables.

**Comment by tobyplowy** [comment]
@LordStephen77 I don't think this needs to be here anymore :)
